name: Save bot example

on:
  push:
    branches:
    - dev

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image:  node:12.4-alpine

    steps:
    - uses: actions/checkout@v1

    - run: npm ci
      working-directory: .

    - run: node saveBot.js
      id: savebot
      working-directory: .
      env:
        CSML_CLIENT_URL: https://md-api-clients.ngrok.io
        CSML_CLIENT_API_KEY: ${{ secrets.CSML_CLIENT_API_KEY }}
        CSML_CLIENT_API_SECRET: ${{ secrets.CSML_CLIENT_API_SECRET }}