name: Save bot example

on:
  push:
    branches:
      - dev
    tags:
      - '*'

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image:  node:12.4-alpine

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
        working-directory: .

      - name: Test get params
        uses: mdarriga/tmp-test-action@v3
        with:
          build: true
          save: true
          create_label: true

      - name: Save
        run: node index.js
        id: savebot
        working-directory: .
        # with:
        #   save: true
        #   build: true
        env:
          CSML_CLIENT_URL: https://md-api-clients.ngrok.io
          CSML_CLIENT_API_KEY: ${{ secrets.CSML_CLIENT_API_KEY }}
          CSML_CLIENT_API_SECRET: ${{ secrets.CSML_CLIENT_API_SECRET }}
    # - name: CSML - update bot on dev push
    #   uses: mdarriga/csml-bot-sync-action@v4
    #   env:
    #     CSML_CLIENT_URL: https://md-api-clients.ngrok.io
    #     CSML_CLIENT_API_KEY: ${{ secrets.CSML_CLIENT_API_KEY }}
    #     CSML_CLIENT_API_SECRET: ${{ secrets.CSML_CLIENT_API_SECRET }}
