name: Save bot example

on:
  push:
    branches:
      - dev
    tags:
      - '*'

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Save
        run: node index.js
        with:
          save: true
          build: true
